name: Generate Dapp Frontend build

on: workflow_dispatch

jobs:
  build_frontend_dapp:
    name: Build Frontend Dapp
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3
      - id: commit
        uses: prompt/actions-commit-hash@v2
      - name: Install Dependencies
        run: yarn install
      - name: Build Frontend Dapp
        run: yarn build