name: Release Dapp Frontend build to IPFS

on: workflow_dispatch

jobs:
  build_frontend_dapp:
    name: Build Frontend Dapp
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit.outputs.hash }}
      commit_short_hash: ${{ steps.commit.outputs.short }}
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3
      - id: commit
        uses: prompt/actions-commit-hash@v2
      - name: Install Dependencies
        run: yarn install
      - name: Build Frontend Dapp
        run: yarn build
      - name: Upload Frontend Build to IPFS (Pinata)
        id: upload_frontend_build
        uses: aquiladev/ipfs-action@master
        with:
          path: ./apps/web/build
          service: pinata
          pinataKey: ${{ secrets.PINATA_API_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET_API_KEY }}
      - name: Generate CIDv1
        id: generate_cidv1
        uses: money-on-chain/convert-cidv0-cidv1@v1.0.0
        with: 
          cidv0: ${{ steps.upload_frontend_build.outputs.hash }}