name: Release Dapp Frontend build to IPFS

on: workflow_dispatch

jobs:
  build_frontend_dapp:
    name: Build Frontend Dapp
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit.outputs.hash }}
      commit_short_hash: ${{ steps.commit.outputs.short }}
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3
      - id: commit
        uses: prompt/actions-commit-hash@v2
      - name: Install Dependencies
        run: yarn install
      - name: Build Frontend Dapp
        run: yarn build
      - name: Upload Frontend Build to IPFS (Pinata)
        id: upload_frontend_build
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        with:
          pin-name: "Heaven's Door Dapp Frontend ${{ steps.commit.outputs.commit_short_hash }}"
          path: './app/web/build'
          pinata-api-key:  ${{ secrets.PINATA_API_KEY }}}
          pinata-secret-api-key:  ${{ secrets.PINATA_SECRET_API_KEY }}
          verbose: true
          remove-old: false
